# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2
orbs:
  android: circleci/android@1.0
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: ccistaging/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sdk/build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "sdk_stub/build.gradle" }}
      - run: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
      -name: Unit Test
        run: ./gradlew testDebugUnitTest


